### ISSUE TITLE
Compat Issue since last Update with C2ME

### ISSUE THREAD

**Issue by suerion** [McMellonTeam/easierworldcreator#17] opened 2024-09-30 16:56 UTC
Hey, i had an issue since your last Update with C2ME, it throus me allways EOFException
```
[18:49:00] [c2me-worker-3/INFO]: [STDERR]: java.io.EOFException
[18:49:00] [c2me-worker-3/INFO]: [STDERR]: 	at java.base/java.io.RandomAccessFile.readFully(RandomAccessFile.java:500)
[18:49:00] [c2me-worker-3/INFO]: [STDERR]: 	at java.base/java.io.RandomAccessFile.readInt(RandomAccessFile.java:892)
[18:49:00] [c2me-worker-3/INFO]: [STDERR]: 	at net.rodofire.easierworldcreator.util.ChunkUtil.findChunkInFile(ChunkUtil.java:79)
[18:49:00] [c2me-worker-3/INFO]: [STDERR]: 	at net.rodofire.easierworldcreator.util.ChunkUtil.addChunk(ChunkUtil.java:104)
[18:49:00] [c2me-worker-3/INFO]: [STDERR]: 	at net.minecraft.class_2794.handler$ceb000$easierworldcreator$addGeneratedChunk(class_2794.java:1206)
[18:49:00] [c2me-worker-3/INFO]: [STDERR]: 	at net.minecraft.class_2794.method_12102(class_2794.java:383)
[18:49:00] [c2me-worker-3/INFO]: [STDERR]: 	at net.minecraft.class_9310.method_57610(class_9310.java:103)
[18:49:00] [c2me-worker-3/INFO]: [STDERR]: 	at net.minecraft.class_9770.mixinextras$bridge$doWork$14(class_9770.java)
[18:49:00] [c2me-worker-3/INFO]: [STDERR]: 	at net.minecraft.class_9770.wrapOperation$bhg000$c2me-opts-chunk-access$runGenerationTask(class_9770.java:526)
[18:49:00] [c2me-worker-3/INFO]: [STDERR]: 	at net.minecraft.class_9770.method_60560(class_9770.java:33)
[18:49:00] [c2me-worker-3/INFO]: [STDERR]: 	at com.ishland.c2me.rewrites.chunksystem.common.statuses.VanillaWorldGenerationDelegate.lambda$upgradeToThis$8(VanillaWorldGenerationDelegate.java:123)
[18:49:00] [c2me-worker-3/INFO]: [STDERR]: 	at com.ishland.c2me.base.common.scheduler.ScheduledTask.run(ScheduledTask.java:22)
[18:49:00] [c2me-worker-3/INFO]: [STDERR]: 	at com.ishland.flowsched.executor.WorkerThread.pollTasks(WorkerThread.java:57)
[18:49:00] [c2me-worker-3/INFO]: [STDERR]: 	at com.ishland.flowsched.executor.WorkerThread.run(WorkerThread.java:27)
```

Loading Minecraft 1.21.1 with Fabric Loader 0.16.5
https://mclo.gs/cBswF1A

**Comment by RodoFire** [comment] 2024-09-30 18:07
I can reproduce this issue in 1.21.1. 1.20.1 isn't impacted nor 1.20.4.

**Comment by RodoFire** [comment] 2024-09-30 18:16
nor 1.20.6

**Comment by suerion** [comment] 2024-10-01 08:58
Will try disable other mods and come back to you. To help debug this issue.

**Comment by RodoFire** [comment] 2024-10-08 18:55
the issue is now fixed. Will release the different versions on modrinth/curseforge soon

**Closed as completed by RodoFire** 2024-10-08 18:55 UTC
Labels: bug

**Comment by suerion** [comment] 2024-10-08 19:34
Thanks for the the good work, hope i could be helpful :)

**Comment by RodoFire** [comment] 2024-10-09 18:21
yeah, It's really great to improve mod compatibility. I just released the new version (★‿★)
